name: Generate Docs
# for Github-Pages

on:
  push:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:
#  run-quality-control:
#    uses: ./.github/workflows/qc_tests.yml
  build-pages:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
#    needs:
#      - run-quality-control
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          submodules: true  # for grabbing readme-files

      - name: Build and Push Pages 🧱
        uses: sphinx-notes/pages@v3
        with:
          checkout: false
          pyproject_extras: ""
          # currently needed because action begins to analyze root pyproject.toml
