name: Generate Docs
# for Github-Pages

on:
  push:
    branches: [ "main" ]
  workflow_call:

jobs:
#  run-quality-control:
#    uses: ./.github/workflows/qc_tests.yml
  build-pages:
    runs-on: ubuntu-latest
    needs:
#      - run-quality-control
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:

      - name: Build and Push Pages 🧱
        uses: sphinx-notes/pages@v3
